CREATE DATABASE eBroker;

USE eBroker
go

CREATE TABLE [Role] (
	RoleID INT PRIMARY KEY IDENTITY (1, 1)
	, RoleName NVARCHAR(100)
	, IsAdminAccess BIT
)

INSERT INTO [Role] (RoleName,IsAdminAccess)
VALUES ('ADMINISTRATOR', 1), ('TRADER', 0)

CREATE TABLE [User] (
	UserID INT PRIMARY KEY IDENTITY (20210, 1)
	, FirstName NVARCHAR(100)
	, LastName NVARCHAR(100)
	, EmailAddress NVARCHAR(100)
	, Password NVARCHAR(100)
)

INSERT INTO [USER ] (FIRSTNAME, LASTNAME, EMAILADDRESS, PASSWORD)
VALUES ('Prasun', 'Guchhait', 'prasun.guchhait@nagp.com', 'Passw0rs')
, ('NAGP', 'Admin', 'admin@nagp.com', 'Admin@007')

CREATE TABLE [UserRole](
	UserRoleID INT PRIMARY KEY IDENTITY (1,1)
	, UserID INT FOREIGN KEY REFERENCES [USER](USERID)
	, RoleID INT FOREIGN KEY REFERENCES [ROLE](ROLEID)
)

INSERT INTO UserRole (USERID, ROLEID)
VALUES (20211, 1), (20210, 2)

CREATE TABLE Account (
	AccountID INT PRIMARY KEY IDENTITY (210, 1), 
	UserID INT FOREIGN KEY REFERENCES [USER](USERID), 
	DmatAccountNumber NVARCHAR(50), 
	AvailableBalance DECIMAL(10, 2), 
	IsActive BIT
)

INSERT INTO ACCOUNT (USERID, DMATACCOUNTNUMBER, AVAILABLEBALANCE, ISACTIVE)
VALUES (20210, '1234-5678-9012-3456', 50000.10, 1)

CREATE TABLE STOCK (
	StockID INT PRIMARY KEY IDENTITY (1, 1)
	, StockName NVARCHAR(100)
	, Price DECIMAL(10, 2)
	, DayLow DECIMAL(10, 2)
	, DayHigh DECIMAL (10, 2)
	, IsActive BIT
)

INSERT INTO STOCK
VALUES ('Reliance Industries', 2499.40, 2425.00, 2459.95, 1)
, ('Tata Motors', 494.35, 489.55, 498.50, 1)
, ('HDFC Bank', 1526.10, 1525.55, 1554.70, 1)
, ('Zomato', 146.55, 1460,148.65, 1)
, ('Vodafone Idea', 16.05, 214.45, 16.40, 1)

CREATE TABLE TradeType (
	TypeID INT PRIMARY KEY IDENTITY (1, 1)
	, TradeName NVARCHAR(100)
	, IsActive BIT
)

INSERT INTO TradeType
VALUES ('BUY', 1), ('SELL', 1)


CREATE TABLE TradeHistory (
	TradeID INT PRIMARY KEY IDENTITY (1, 1)
	, UserID INT FOREIGN KEY REFERENCES [USER](USERID)
	, TradeDate DATETIME
	, TradeType INT FOREIGN KEY REFERENCES TRADETYPE(TYPEID)
	, StockID INT FOREIGN KEY REFERENCES STOCK(STOCKID)
	, StockQty INT
	, Amount Decimal(10, 2)
)


CREATE TABLE UserPortfolio (
	RecordID INT PRIMARY KEY IDENTITY (1,1), 
	UserID INT FOREIGN KEY REFERENCES [USER](userid), 
	StockID INT FOREIGN KEY REFERENCES [Stock](STOCKID), 
	StockQty INT,
	InvestedAmount DECIMAL(12, 2),
	isActive BIT
)
